
from exception import greet

print(greet('Alex'))